[package]
authors = ["Eric Trombly <etrombly@yahoo.com>"]
name = "rgeo"
version = "0.1.0"
description = "Offline reverse geocoding library using geonames db"
license = "mit"
repository = "https://github.com/etrombly/rgeo"

[dependencies]
bincode = "1.0.0"
csv = "1.0.0-beta.5"
lazy_static = "1.0.0"
serde = "1.0.42"
serde_derive = "1.0.42"
serde_json = "1.0.16"

[dependencies.kdtree]
version = "0.5"
features = ["serialize"]

[profile.release]
lto = true
