[package]
authors = ["Eric Trombly <etrombly@yahoo.com>"]
name = "rgeo"
version = "0.1.0"

[dependencies]
bincode = "1.0.0"
csv = "1.0.0-beta.5"
lazy_static = "1.0.0"
serde = "1.0.42"
serde_derive = "1.0.42"
serde_json = "1.0.16"

[dependencies.kdtree]
path = "../kdtree-rs"
[profile.release]
lto = true
