[package]
authors = ["Eric Trombly <etrombly@yahoo.com>"]
name = "rgeo"
version = "0.2.1"
description = "Offline reverse geocoding library using geonames db"
keywords = ["reverse", "geocode", "geocoding", "geo", "location"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/etrombly/rgeo"
readme = "README.md"
edition = "2018"

[dependencies]
bincode = "1.0.1"
csv = "1.0.2"
lazy_static = "1.2.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"

[dependencies.kdtree]
version = "0.5.1"
features = ["serialize"]

[profile.release]
lto = true
